name: build

on:
  push:
    branches: master
  pull_request:

jobs:
  sanity:
    name: sanity / ${{ matrix.toxenv }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.11"]
        toxenv: [django_not_installed, flake8, pylint, readme]

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Execute tests
        run: |
            pip install -U pip poetry tox
            poetry install -E for_tests

            export TOXENV=${{ matrix.toxenv }}
            export PYTHON=${{ matrix.python-version }}
            tox

  build_and_package_sanity:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.11"]

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Build
        run: |
            pip install -U pip poetry tox
            poetry install -E for_tests

            ./scripts/build.sh
